# 🚙 **Разработка интеллектуальной системы оценки для «AutoValue AI»**

Автор: Якунин Михаил

Дата: ____ август 2026 г.

***По этой ссылке можно посмотреть проекта и скачать последнюю версию: https://github.com/MEYakunin/Sprint16_Predictive_Model_Car_Prices.git***

## Цель проекта

## Задача проекта

## Описание данных

## Содержание <a id="content"></a>

* [1. Импорт библиотек и загрузка данных](#1)
* [2. ](#2)
* [3. ](#3)
  * [3.1. ](#3.1)

## [Этап 1. Импорт библиотек и загрузка данных <a id=1></a>](#content)

### 1.1 Подготовка среды и библиотек

In [1]:
# Установка необходимых библиотек
# !pip install -r requirements.txt

In [2]:
# Импорт библиотек
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Устанавка константных параметров
RANDOM_STATE = 42
TEST_SIZE = 0.2

# Пути к данным
DATA_PATH = 'datasets/'
FILES = {
    'train': 'ds_s16_train_data.csv',
    'test': 'ds_s16_test_data.csv'
}

In [4]:
# Настройки Pandas для отображения DataFrame
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.float_format', '{:.4f}'.format)
pd.set_option('display.memory_usage', True)

# Настройка стиля графиков
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("viridis")

### 1.2 Загрузка данных и первичная информация о данных

In [8]:
# Загрузка CSV-файлов
train_df = pd.read_csv(DATA_PATH + FILES['train'])
test_df = pd.read_csv(DATA_PATH + FILES['test'])

# Создание словаря c датафреймами
dataframes = {
    'train': train_df,
    'test': test_df
}

In [6]:
# Создаем функцию для отображения данных
def primary_info(df, name):
    print('='*50)
    print(f'Информация о таблице: {name}')
    print('='*50)
    display(df.head(5))
    df.info()
    display(df.describe(include='all').T)
    print()

In [9]:
# Выводим первичную информацию 
for name, df in dataframes.items():
    primary_info(df, name)

==================================================
Информация о таблице: train
==================================================

,make_year,mileage_kmpl,engine_cc,fuel_type,owner_count,brand,transmission,color,service_history,accidents_reported,insurance_valid,price_rub,region
0,2002,9.7000,1800,Diesel,2,Hyundai,Manual,Silver,Partial,0,No,242073,Урал
1,2004,16.1000,1500,Diesel,3,Hyundai,Manual,Black,Unknown,0,No,426029,Москва
2,2005,10.5100,5000,Diesel,2,Ford,Manual,Gray,Full,0,No,727050,Юг
3,2019,14.2700,2000,Petrol,5,Hyundai,Manual,White,Full,1,Yes,753168,Дальний Восток
4,2015,21.7200,1000,Petrol,1,Toyota,Automatic,Black,Full,0,Yes,733390,Сибирь

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   make_year           8000 non-null   int64
 1   mileage_kmpl        8000 non-null   float64
 2   engine_cc           8000 non-null   int64
 3   fuel_type           8000 non-null   str
 4   owner_count         8000 non-null   int64
 5   brand               8000 non-null   str
 6   transmission        8000 non-null   str
 7   color               8000 non-null   str
 8   service_history     8000 non-null   str
 9   accidents_reported  8000 non-null   int64
 10  insurance_valid     8000 non-null   str
 11  price_rub           8000 non-null   int64
 12  region              8000 non-null   str
dtypes: float64(1), int64(5), str(7)
memory usage: 812.6 KB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
make_year,8000.0000,NaN,NaN,NaN,2009.2213,8.3887,1995.0000,2002.0000,2009.0000,2017.0000,2023.0000
mileage_kmpl,8000.0000,NaN,NaN,NaN,17.9463,5.0156,5.0000,14.5300,17.9700,21.3500,35.0000
engine_cc,8000.0000,NaN,NaN,NaN,2289.6875,1289.8121,800.0000,1200.0000,2000.0000,3000.0000,5000.0000
fuel_type,8000,3,Petrol,3990,NaN,NaN,NaN,NaN,NaN,NaN,NaN
owner_count,8000.0000,NaN,NaN,NaN,3.0011,1.4192,1.0000,2.0000,3.0000,4.0000,5.0000
brand,8000,10,Nissan,870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transmission,8000,2,Manual,4812,NaN,NaN,NaN,NaN,NaN,NaN,NaN
color,8000,6,White,1366,NaN,NaN,NaN,NaN,NaN,NaN,NaN
service_history,8000,3,Full,3985,NaN,NaN,NaN,NaN,NaN,NaN,NaN
accidents_reported,8000.0000,NaN,NaN,NaN,0.4879,0.6938,0.0000,0.0000,0.0000,1.0000,5.0000
insurance_valid,8000,2,Yes,6356,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_rub,8000.0000,NaN,NaN,NaN,683647.8721,264923.4986,95000.0000,493857.0000,663866.0000,855056.0000,1676525.0000
region,8000,6,Юг,1408,NaN,NaN,NaN,NaN,NaN,NaN,NaN

==================================================
Информация о таблице: test
==================================================

,make_year,mileage_kmpl,engine_cc,fuel_type,owner_count,brand,transmission,color,service_history,accidents_reported,insurance_valid,price_rub,region
0,2015,12.0900,5000,Diesel,1,Nissan,Automatic,White,Full,2,No,1213351,Москва
1,2016,14.0300,800,Petrol,4,Chevrolet,Manual,White,Partial,0,Yes,586881,Дальний Восток
2,2005,20.4000,2000,Petrol,1,Kia,Manual,Blue,Full,2,Yes,650752,Сибирь
3,1996,25.0900,800,Diesel,3,Volkswagen,Manual,Silver,Full,0,Yes,320452,Урал
4,1995,19.2500,5000,Diesel,5,Hyundai,Automatic,Black,Partial,0,No,694911,СПб

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   make_year           2000 non-null   int64
 1   mileage_kmpl        2000 non-null   float64
 2   engine_cc           2000 non-null   int64
 3   fuel_type           2000 non-null   str
 4   owner_count         2000 non-null   int64
 5   brand               2000 non-null   str
 6   transmission        2000 non-null   str
 7   color               2000 non-null   str
 8   service_history     2000 non-null   str
 9   accidents_reported  2000 non-null   int64
 10  insurance_valid     2000 non-null   str
 11  price_rub           2000 non-null   int64
 12  region              2000 non-null   str
dtypes: float64(1), int64(5), str(7)
memory usage: 203.3 KB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
make_year,2000.0000,NaN,NaN,NaN,2009.1495,8.3161,1995.0000,2002.0000,2009.0000,2016.0000,2023.0000
mileage_kmpl,2000.0000,NaN,NaN,NaN,18.0184,5.0658,5.0000,14.5700,18.0050,21.3825,34.3800
engine_cc,2000.0000,NaN,NaN,NaN,2276.9000,1297.3928,800.0000,1200.0000,1800.0000,3000.0000,5000.0000
fuel_type,2000,3,Petrol,978,NaN,NaN,NaN,NaN,NaN,NaN,NaN
owner_count,2000.0000,NaN,NaN,NaN,3.0130,1.4180,1.0000,2.0000,3.0000,4.0000,5.0000
brand,2000,10,Tesla,222,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transmission,2000,2,Manual,1173,NaN,NaN,NaN,NaN,NaN,NaN,NaN
color,2000,6,Gray,365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
service_history,2000,3,Full,1002,NaN,NaN,NaN,NaN,NaN,NaN,NaN
accidents_reported,2000.0000,NaN,NaN,NaN,0.5095,0.6951,0.0000,0.0000,0.0000,1.0000,4.0000
insurance_valid,2000,2,Yes,1578,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_rub,2000.0000,NaN,NaN,NaN,675791.9355,268019.5989,95000.0000,481477.0000,649284.0000,845969.5000,1629774.0000
region,2000,6,Сибирь,357,NaN,NaN,NaN,NaN,NaN,NaN,NaN